Details screen
kenzywa/table-application pull request #1
Opened 2021-03-26 16:41 UTC by kenzywa

2021-03-27 17:36 UTC, damencki requested changes

2021-03-27 17:36 UTC, damencki commented on TableApplication.xcodeproj/xcuserdata/roman.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
Add file to gitignore

2021-03-27 17:36 UTC, damencki commented on TableApplication/Employee.swift
> +    var age: String
Incorrect type

2021-03-27 17:36 UTC, damencki commented on TableApplication/Employee.swift
> +    var numberPhone: String
Inorrect type

2021-03-27 17:36 UTC, damencki commented on TableApplication/SecondViewController.swift
> +class SecondViewController: UIViewController {
Incorrect class name

2021-03-27 17:36 UTC, damencki commented on TableApplication/SecondViewController.swift
> +        self.view.addSubview(buttonToSave)
extract to method

2021-03-27 17:36 UTC, damencki commented on TableApplication/SecondViewController.swift
> +                return
Where is error handling?

2021-03-27 17:36 UTC, damencki commented on TableApplication/ViewController.swift
> +        self.title = "Table of Employees"
Create private struct with constants

2021-03-27 17:36 UTC, damencki commented on TableApplication/ViewController.swift
> +
delete empty line

2021-03-27 17:36 UTC, damencki commented on TableApplication/ViewController.swift
> +                return
error handling?

2021-03-27 17:36 UTC, damencki commented on TableApplication/ViewController.swift
> +        return 80.0
struct with constants

2021-03-27 17:36 UTC, damencki commented on TableApplication/delegateProtocol.swift
> +protocol DataDelegate {
incorrect protocol name

2021-03-27 21:10 UTC, kenzywa commented on TableApplication/Employee.swift
> +    var age: String
Solved

2021-03-27 21:10 UTC, kenzywa commented on TableApplication/Employee.swift
> +    var numberPhone: String
Solved

2021-03-27 21:14 UTC, kenzywa commented on TableApplication/SecondViewController.swift
> +class SecondViewController: UIViewController {
Solved

2021-03-28 09:26 UTC, kenzywa commented on TableApplication/ViewController.swift
> +        return 80.0
Solved

2021-03-28 09:26 UTC, kenzywa commented on TableApplication/ViewController.swift
> +
Solved

2021-03-28 09:26 UTC, kenzywa commented on TableApplication/ViewController.swift
> +        self.title = "Table of Employees"
Solved

2021-03-28 09:35 UTC, kenzywa commented on TableApplication/delegateProtocol.swift
> +protocol DataDelegate {
Solved

2021-03-28 09:52 UTC, kenzywa commented on TableApplication.xcodeproj/xcuserdata/roman.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
Solved

2021-03-28 10:05 UTC, kenzywa commented on TableApplication/SecondViewController.swift
> +        self.view.addSubview(buttonToSave)
Solved

2021-03-28 10:14 UTC, kenzywa commented on TableApplication/ViewController.swift
> +                return
Solved

2021-03-28 10:25 UTC, damencki commented on TableApplication/TableViewController.swift
> +class TableViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, EmployeeEditorDelegate {
incorrct class name.

use  EmployeeListViewController

2021-03-28 10:43 UTC, damencki reviewed
nice job

2021-03-28 10:45 UTC, merged