Created list of tasks
kenzywa/table-application pull request #13
Opened 2021-04-25 19:26 UTC by kenzywa

Created list of tasks with properties of task.

2021-04-25 21:37 UTC, damencki requested changes

2021-04-25 21:37 UTC, damencki commented on TableApplication/Task/Task.swift
> +    var start_date : String
should be date

2021-04-25 21:37 UTC, damencki commented on TableApplication/Task/Task.swift
> +    var status : String
should be enum

2021-04-25 21:37 UTC, damencki commented on TableApplication/Task/Task.swift
> +    var employee : String
incorrect type

2021-04-25 21:37 UTC, damencki commented on TableApplication/Task/Task.swift
> +    var project : String
incorrect type

2021-04-25 21:37 UTC, damencki commented on TableApplication/Task/TaskListViewController.swift
> +        taskListTableView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
use autolayout or autoresizing mask

2021-04-25 21:37 UTC, damencki commented on TableApplication/Task/TaskListViewController.swift
> +//    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
delete comments

2021-04-26 20:49 UTC, kenzywa commented on TableApplication/Task/TaskListViewController.swift
> +//    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
Solved

2021-04-26 20:49 UTC, kenzywa commented on TableApplication/Task/Task.swift
> +    var project : String
Solved

2021-04-26 20:49 UTC, kenzywa commented on TableApplication/Task/Task.swift
> +    var employee : String
Solved

2021-04-26 20:49 UTC, kenzywa commented on TableApplication/Task/Task.swift
> +    var status : String
Solved

2021-04-26 20:49 UTC, kenzywa commented on TableApplication/Task/Task.swift
> +    var start_date : String
Solved

2021-04-26 20:56 UTC, kenzywa commented on TableApplication/Task/TaskListViewController.swift
> +        taskListTableView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
Solved

2021-04-26 21:05 UTC, damencki requested changes

2021-04-26 21:05 UTC, damencki commented on TableApplication/Task/TaskListViewController.swift
> +        self.taskListTableView.frame = view.bounds
delete setup frame

2021-04-26 21:19 UTC, damencki approved these changes

2021-04-26 21:19 UTC, merged